dist: xenial

services:
    - docker
    - postgresql

cache:
    yarn: true
    directories:
        - node_modules

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker pull trufflesuite/ganache-cli:v6.8.1
  - mkdir -p ./db_ganache
  - docker run -d -p 8545:8545 --name my_ganache -v "$PWD/db_ganache":/app/db_ganache trufflesuite/ganache-cli:v6.8.1 --mnemonic "width whip dream dress captain vessel mix drive oxygen broken soap bone" --db "db_ganache/"


jobs:
  allow_failures:
    - stage: test
  include:
    - stage: "Deploy Contracts"
      language: node_js
      node_js:
        - "lts/dubnium"
      install:
        - (cd workspace-blockchain && yarn)
      script:
        - (cd workspace-blockchain && yarn deploy:ganache:local)
        - docker exec -it my_ganache ls -la db_ganache
    - stage: test
      language: android
      jdk: openjdk10
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-29.0.2
          - android-29
          - extra-android-m2repository
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      install:
        - (cd workspace-android && ./gradlew assemble)
      script:
        - docker exec -it my_ganache ls -la db_ganache
        - (cd workspace-android && ./gradlew test --stacktrace)
    -
      language: node_js
      node_js: "lts/dubnium"
      install:
        - (cd workspace-blockchain && yarn)
      script:
        - (cd workspace-blockchain && yarn test:ci)
        - (cd workspace-blockchain && yarn coverage:ci)
        - (cd workspace-blockchain && yarn lint)
        - (cd workspace-blockchain && npx codechecks)
    -
      language: node_js
      node_js: "lts/dubnium"
      install:
        - (cd workspace-webui && yarn)
      script:
        - (cd workspace-webui && yarn lint)
    -
      language: node_js
      node_js: "lts/dubnium"
      install:
        - (cd workspace-cache-server && yarn)
      before_script:
        - psql -c 'create database starterkitcache;' -U postgres
        - psql -c 'create table setvalue(id int primary key, newvalue integer, tx text unique, sender text);' -U postgres
      script:
        - (cd workspace-cache-server && yarn test)
